insert into Borrower (BId, Name, Town, StreetName, StreetNumber, PostalCode) values (1, 'Jennifer Rose', 'Mississippi', 'Pearson', '472', '39210');
insert into Borrower (BId, Name, Town, StreetName, StreetNumber, PostalCode) values (2, 'Michael Olson', 'California', 'Stephen', '5660', '95298');
insert into Borrower (BId, Name, Town, StreetName, StreetNumber, PostalCode) values (3, 'Fred Wells', 'Texas', 'Heffernan', '06', '78778');
insert into Borrower (BId, Name, Town, StreetName, StreetNumber, PostalCode) values (4, 'Victor Mendoza', 'Wisconsin', 'Moulton', '6190', '53405');
insert into Borrower (BId, Name, Town, StreetName, StreetNumber, PostalCode) values (5, 'Todd Tucker', 'Florida', 'Old Gate', '353', '33134');
insert into Borrower (BId, Name, Town, StreetName, StreetNumber, PostalCode) values (6, 'Bobby Shaw', 'California', 'Cordelia', '59749', '92844');
insert into Borrower (BId, Name, Town, StreetName, StreetNumber, PostalCode) values (7, 'Susan Chapman', 'Florida', 'Sage', '47', '33310');
insert into Borrower (BId, Name, Town, StreetName, StreetNumber, PostalCode) values (8, 'Teresa Adams', 'Illinois', 'Valley Edge', '4787', '60078');
insert into Borrower (BId, Name, Town, StreetName, StreetNumber, PostalCode) values (9, 'Susan Franklin', 'Connecticut', 'Schlimgen', '72', '06854');
insert into Borrower (BId, Name, Town, StreetName, StreetNumber, PostalCode) values (10, 'Marilyn Mcdonald', 'West Virginia', 'Loftsgordon', '15', '25331');
insert into Borrower (BId, Name, Town, StreetName, StreetNumber, PostalCode) values (11, 'Frances Hansen', 'North Carolina', 'Bultman', '4852', '27110');
insert into Borrower (BId, Name, Town, StreetName, StreetNumber, PostalCode) values (12, 'Marilyn Rice', 'Florida', 'Oxford', '0512', '33421');
insert into Borrower (BId, Name, Town, StreetName, StreetNumber, PostalCode) values (13, 'Carolyn Franklin', 'New York', 'Kipling', '1', '11436');
insert into Borrower (BId, Name, Town, StreetName, StreetNumber, PostalCode) values (14, 'Willie Powell', 'Alabama', 'Thackeray', '4244', '36641');
insert into Borrower (BId, Name, Town, StreetName, StreetNumber, PostalCode) values (15, 'Walter Crawford', 'Florida', 'Monument', '8', '33310');
insert into Borrower (BId, Name, Town, StreetName, StreetNumber, PostalCode) values (16, 'Kathleen Schmidt', 'Arkansas', 'Atwood', '76', '72222');
insert into Borrower (BId, Name, Town, StreetName, StreetNumber, PostalCode) values (17, 'Johnny Sanders', 'Iowa', 'Pepper Wood', '2612', '51110');
insert into Borrower (BId, Name, Town, StreetName, StreetNumber, PostalCode) values (18, 'Theresa Stevens', 'Florida', 'High Crossing', '18831', '32225');
insert into Borrower (BId, Name, Town, StreetName, StreetNumber, PostalCode) values (19, 'Marilyn Torres', 'Florida', 'Grim', '160', '34108');
insert into Borrower (BId, Name, Town, StreetName, StreetNumber, PostalCode) values (20, 'Virginia Campbell', 'Tennessee', 'Coolidge', '06', '37405');
insert into Borrower (BId, Name, Town, StreetName, StreetNumber, PostalCode) values (21, 'Christine Phillips', 'Pennsylvania', 'Buell', '01822', '17622');
insert into Borrower (BId, Name, Town, StreetName, StreetNumber, PostalCode) values (22, 'Stephanie Butler', 'New York', 'Anniversary', '2699', '10105');
insert into Borrower (BId, Name, Town, StreetName, StreetNumber, PostalCode) values (23, 'Nancy Pierce', 'Louisiana', 'Superior', '94742', '70142');
insert into Borrower (BId, Name, Town, StreetName, StreetNumber, PostalCode) values (24, 'Julia Roberts', 'Oklahoma', 'Glendale', '6', '73167');
insert into Borrower (BId, Name, Town, StreetName, StreetNumber, PostalCode) values (25, 'Shawn Rogers', 'North Carolina', 'Grayhawk', '8', '27705');
insert into Borrower (BId, Name, Town, StreetName, StreetNumber, PostalCode) values (26, 'Gerald Thompson', 'Pennsylvania', 'Bluestem', '55', '15266');
insert into Borrower (BId, Name, Town, StreetName, StreetNumber, PostalCode) values (27, 'William Hanson', 'Florida', 'Atwood', '54913', '34620');
insert into Borrower (BId, Name, Town, StreetName, StreetNumber, PostalCode) values (28, 'Marilyn Patterson', 'Pennsylvania', 'Orin', '03', '17110');
insert into Borrower (BId, Name, Town, StreetName, StreetNumber, PostalCode) values (29, 'Diane Spencer', 'Florida', 'Washington', '58548', '32825');
insert into Borrower (BId, Name, Town, StreetName, StreetNumber, PostalCode) values (30, 'Beverly Henderson', 'Washington', 'Debra', '0', '98140');
insert into Borrower (BId, Name, Town, StreetName, StreetNumber, PostalCode) values (31, 'Sarah Thompson', 'California', 'Swallow', '91', '95205');
insert into Borrower (BId, Name, Town, StreetName, StreetNumber, PostalCode) values (32, 'Angela Cox', 'Illinois', 'Truax', '9', '60619');
insert into Borrower (BId, Name, Town, StreetName, StreetNumber, PostalCode) values (33, 'Justin Gomez', 'Tennessee', 'Forest', '7282', '37919');
insert into Borrower (BId, Name, Town, StreetName, StreetNumber, PostalCode) values (34, 'Dorothy Burns', 'Texas', 'Barnett', '70404', '77005');
insert into Borrower (BId, Name, Town, StreetName, StreetNumber, PostalCode) values (35, 'Mark Barnes', 'Alabama', 'Loomis', '10', '36605');
insert into Borrower (BId, Name, Town, StreetName, StreetNumber, PostalCode) values (36, 'Samuel Johnson', 'Ohio', 'Lillian', '3', '45403');
insert into Borrower (BId, Name, Town, StreetName, StreetNumber, PostalCode) values (37, 'Rebecca Phillips', 'South Carolina', 'Daystar', '30163', '29305');
insert into Borrower (BId, Name, Town, StreetName, StreetNumber, PostalCode) values (38, 'Charles Lane', 'Mississippi', 'Merchant', '77', '39204');
insert into Borrower (BId, Name, Town, StreetName, StreetNumber, PostalCode) values (39, 'Nicholas Lynch', 'Florida', 'Donald', '36', '34479');
insert into Borrower (BId, Name, Town, StreetName, StreetNumber, PostalCode) values (40, 'Edward Martin', 'Oregon', 'Marquette', '96294', '97232');
insert into Borrower (BId, Name, Town, StreetName, StreetNumber, PostalCode) values (41, 'Lisa Andrews', 'Mississippi', 'Morning', '5622', '39534');
insert into Borrower (BId, Name, Town, StreetName, StreetNumber, PostalCode) values (42, 'Robert Reynolds', 'Alabama', 'Cardinal', '241', '35244');
insert into Borrower (BId, Name, Town, StreetName, StreetNumber, PostalCode) values (43, 'Susan Walker', 'Louisiana', 'Corben', '8213', '70174');
insert into Borrower (BId, Name, Town, StreetName, StreetNumber, PostalCode) values (44, 'Judith Gomez', 'Virginia', 'Park Meadow', '46', '20189');
insert into Borrower (BId, Name, Town, StreetName, StreetNumber, PostalCode) values (45, 'Ernest Rodriguez', 'Kentucky', 'Brentwood', '267', '40596');
insert into Borrower (BId, Name, Town, StreetName, StreetNumber, PostalCode) values (46, 'Jerry Bowman', 'Nevada', 'Weeping Birch', '04', '89074');
insert into Borrower (BId, Name, Town, StreetName, StreetNumber, PostalCode) values (47, 'Betty Kelley', 'Minnesota', 'Rieder', '86', '55551');
insert into Borrower (BId, Name, Town, StreetName, StreetNumber, PostalCode) values (48, 'Harold Ellis', 'Utah', 'International', '16296', '84105');
insert into Borrower (BId, Name, Town, StreetName, StreetNumber, PostalCode) values (49, 'Jimmy Cunningham', 'Michigan', 'Continental', '8368', '48919');
insert into Borrower (BId, Name, Town, StreetName, StreetNumber, PostalCode) values (50, 'Judy Banks', 'North Carolina', 'Spaight', '725', '28299');
insert into Borrower (BId, Name, Town, StreetName, StreetNumber, PostalCode) values (51, 'Joe Foster', 'California', 'Bashford', '9130', '92137');
insert into Borrower (BId, Name, Town, StreetName, StreetNumber, PostalCode) values (52, 'Bonnie Riley', 'Michigan', 'Clarendon', '21712', '48217');
insert into Borrower (BId, Name, Town, StreetName, StreetNumber, PostalCode) values (53, 'Terry Little', 'Nebraska', 'Grim', '23089', '68197');
insert into Borrower (BId, Name, Town, StreetName, StreetNumber, PostalCode) values (54, 'Antonio Garcia', 'Washington', 'Coolidge', '38124', '98687');
insert into Borrower (BId, Name, Town, StreetName, StreetNumber, PostalCode) values (55, 'Debra Mason', 'California', 'Drewry', '73', '93786');
insert into Borrower (BId, Name, Town, StreetName, StreetNumber, PostalCode) values (56, 'Betty Hawkins', 'Florida', 'Maple Wood', '4352', '33605');
insert into Borrower (BId, Name, Town, StreetName, StreetNumber, PostalCode) values (57, 'Janet Gray', 'Michigan', 'Armistice', '7549', '49544');
insert into Borrower (BId, Name, Town, StreetName, StreetNumber, PostalCode) values (58, 'Ernest Boyd', 'Alabama', 'Di Loreto', '15', '35244');
insert into Borrower (BId, Name, Town, StreetName, StreetNumber, PostalCode) values (59, 'Emily Young', 'Oklahoma', 'Texas', '00', '73179');
insert into Borrower (BId, Name, Town, StreetName, StreetNumber, PostalCode) values (60, 'Cynthia Armstrong', 'Kansas', 'Anniversary', '673', '66667');
insert into Borrower (BId, Name, Town, StreetName, StreetNumber, PostalCode) values (61, 'Matthew Hicks', 'Maryland', 'Meadow Ridge', '9909', '21265');
insert into Borrower (BId, Name, Town, StreetName, StreetNumber, PostalCode) values (62, 'Janet Howard', 'North Dakota', 'Moland', '6677', '58122');
insert into Borrower (BId, Name, Town, StreetName, StreetNumber, PostalCode) values (63, 'Judith Montgomery', 'Missouri', 'Bay', '8', '64101');
insert into Borrower (BId, Name, Town, StreetName, StreetNumber, PostalCode) values (64, 'Sara Perez', 'Ohio', 'Derek', '75', '44710');
insert into Borrower (BId, Name, Town, StreetName, StreetNumber, PostalCode) values (65, 'Victor Henderson', 'Florida', 'Melvin', '795', '34282');
insert into Borrower (BId, Name, Town, StreetName, StreetNumber, PostalCode) values (66, 'Andrew Burke', 'Florida', 'Westend', '9', '33982');
insert into Borrower (BId, Name, Town, StreetName, StreetNumber, PostalCode) values (67, 'Susan Lawrence', 'Connecticut', 'Donald', '176', '06816');
insert into Borrower (BId, Name, Town, StreetName, StreetNumber, PostalCode) values (68, 'Evelyn Taylor', 'Alabama', 'New Castle', '0', '36119');
insert into Borrower (BId, Name, Town, StreetName, StreetNumber, PostalCode) values (69, 'Amanda Jones', 'Louisiana', 'Kedzie', '2023', '71151');
insert into Borrower (BId, Name, Town, StreetName, StreetNumber, PostalCode) values (70, 'Samuel Sims', 'Ohio', 'Green Ridge', '46', '45419');
insert into Borrower (BId, Name, Town, StreetName, StreetNumber, PostalCode) values (71, 'Melissa Austin', 'North Carolina', 'Cascade', '54723', '28055');
insert into Borrower (BId, Name, Town, StreetName, StreetNumber, PostalCode) values (72, 'Jack Gardner', 'New York', 'Jana', '70', '10115');
insert into Borrower (BId, Name, Town, StreetName, StreetNumber, PostalCode) values (73, 'Billy Green', 'Iowa', 'Nelson', '913', '50330');
insert into Borrower (BId, Name, Town, StreetName, StreetNumber, PostalCode) values (74, 'Joshua Mccoy', 'New Hampshire', 'Burning Wood', '633', '03105');
insert into Borrower (BId, Name, Town, StreetName, StreetNumber, PostalCode) values (75, 'Howard Davis', 'Virginia', 'Roxbury', '37', '22036');
insert into Borrower (BId, Name, Town, StreetName, StreetNumber, PostalCode) values (76, 'Kimberly Bradley', 'Oklahoma', 'Pawling', '2', '73142');
insert into Borrower (BId, Name, Town, StreetName, StreetNumber, PostalCode) values (77, 'Todd Mitchell', 'Oregon', 'Del Sol', '0277', '97229');
insert into Borrower (BId, Name, Town, StreetName, StreetNumber, PostalCode) values (78, 'Rose Elliott', 'Connecticut', 'Merrick', '77830', '06705');
insert into Borrower (BId, Name, Town, StreetName, StreetNumber, PostalCode) values (79, 'Gary Burke', 'Texas', 'Old Gate', '85', '77250');
insert into Borrower (BId, Name, Town, StreetName, StreetNumber, PostalCode) values (80, 'Walter Ramirez', 'Connecticut', 'Meadow Ridge', '1', '06145');
