insert into Lender (LId, Name, Town, StreetName, StreetNumber, PostalCode) values (1, 'Frances Carr', 'Ohio', 'Northwestern', '21', '45505');
insert into Lender (LId, Name, Town, StreetName, StreetNumber, PostalCode) values (2, 'Phyllis James', 'Alabama', 'Summerview', '68495', '35810');
insert into Lender (LId, Name, Town, StreetName, StreetNumber, PostalCode) values (3, 'Kelly Patterson', 'Virginia', 'Gina', '107', '22301');
insert into Lender (LId, Name, Town, StreetName, StreetNumber, PostalCode) values (4, 'James Bowman', 'North Carolina', 'Park Meadow', '61', '28284');
insert into Lender (LId, Name, Town, StreetName, StreetNumber, PostalCode) values (5, 'Kenneth Campbell', 'California', 'Ridge Oak', '22', '94142');
insert into Lender (LId, Name, Town, StreetName, StreetNumber, PostalCode) values (6, 'Douglas Marshall', 'New York', 'Meadow Vale', '046', '14225');
insert into Lender (LId, Name, Town, StreetName, StreetNumber, PostalCode) values (7, 'Nancy Gray', 'Iowa', 'Anniversary', '09', '50706');
insert into Lender (LId, Name, Town, StreetName, StreetNumber, PostalCode) values (8, 'Larry Gutierrez', 'Louisiana', 'Oneill', '576', '70129');
insert into Lender (LId, Name, Town, StreetName, StreetNumber, PostalCode) values (9, 'Diane Wells', 'Michigan', 'Dexter', '7350', '48126');
insert into Lender (LId, Name, Town, StreetName, StreetNumber, PostalCode) values (10, 'Howard Hernandez', 'North Carolina', 'Caliangt', '22', '28405');
insert into Lender (LId, Name, Town, StreetName, StreetNumber, PostalCode) values (11, 'Dennis Holmes', 'Florida', 'Dorton', '681', '33261');
insert into Lender (LId, Name, Town, StreetName, StreetNumber, PostalCode) values (12, 'Lori Fisher', 'Ohio', 'Judy', '260', '44118');
insert into Lender (LId, Name, Town, StreetName, StreetNumber, PostalCode) values (13, 'Judy Wheeler', 'Texas', 'Independence', '4', '77705');
insert into Lender (LId, Name, Town, StreetName, StreetNumber, PostalCode) values (14, 'Sean Long', 'Ohio', 'Mesta', '39', '44720');
insert into Lender (LId, Name, Town, StreetName, StreetNumber, PostalCode) values (15, 'Louis Long', 'Ohio', 'Bay', '388', '43204');
insert into Lender (LId, Name, Town, StreetName, StreetNumber, PostalCode) values (16, 'Nicole Pierce', 'Alabama', 'Anderson', '10230', '35210');
insert into Lender (LId, Name, Town, StreetName, StreetNumber, PostalCode) values (17, 'Henry Jordan', 'Georgia', 'Mcbride', '16', '31136');
insert into Lender (LId, Name, Town, StreetName, StreetNumber, PostalCode) values (18, 'Stephen Ward', 'Louisiana', 'Cambridge', '35', '70815');
insert into Lender (LId, Name, Town, StreetName, StreetNumber, PostalCode) values (19, 'Anna Davis', 'Ohio', 'Browning', '1', '44511');
insert into Lender (LId, Name, Town, StreetName, StreetNumber, PostalCode) values (20, 'Shirley Cox', 'Connecticut', 'Towne', '1079', '06905');
insert into Lender (LId, Name, Town, StreetName, StreetNumber, PostalCode) values (21, 'Diane Lane', 'Florida', 'Charing Cross', '44', '33647');
insert into Lender (LId, Name, Town, StreetName, StreetNumber, PostalCode) values (22, 'Debra Jackson', 'Florida', 'Kim', '692', '32854');
insert into Lender (LId, Name, Town, StreetName, StreetNumber, PostalCode) values (23, 'Jerry Welch', 'California', 'Sullivan', '6739', '90189');
insert into Lender (LId, Name, Town, StreetName, StreetNumber, PostalCode) values (24, 'Christopher Frazier', 'District of Columbia', 'Cherokee', '615', '56944');
insert into Lender (LId, Name, Town, StreetName, StreetNumber, PostalCode) values (25, 'Adam Pierce', 'California', 'Dryden', '8923', '91606');
insert into Lender (LId, Name, Town, StreetName, StreetNumber, PostalCode) values (26, 'Bonnie Scott', 'Idaho', 'Pawling', '6680', '83711');
insert into Lender (LId, Name, Town, StreetName, StreetNumber, PostalCode) values (27, 'Shawn Gibson', 'Tennessee', '1st', '19699', '37220');
insert into Lender (LId, Name, Town, StreetName, StreetNumber, PostalCode) values (28, 'David Ryan', 'Indiana', 'Judy', '81', '46278');
insert into Lender (LId, Name, Town, StreetName, StreetNumber, PostalCode) values (29, 'Linda Fuller', 'Louisiana', 'Macpherson', '0', '70179');
insert into Lender (LId, Name, Town, StreetName, StreetNumber, PostalCode) values (30, 'Brandon Sims', 'New York', 'Hoepker', '464', '14683');
insert into Lender (LId, Name, Town, StreetName, StreetNumber, PostalCode) values (31, 'Jose Peterson', 'Ohio', 'Anzinger', '339', '44321');
insert into Lender (LId, Name, Town, StreetName, StreetNumber, PostalCode) values (32, 'David Williams', 'District of Columbia', 'Atwood', '869', '20520');
insert into Lender (LId, Name, Town, StreetName, StreetNumber, PostalCode) values (33, 'Bobby Lawson', 'Georgia', 'Alpine', '56', '30386');
insert into Lender (LId, Name, Town, StreetName, StreetNumber, PostalCode) values (34, 'Carlos Butler', 'Colorado', 'Debra', '1096', '80045');
insert into Lender (LId, Name, Town, StreetName, StreetNumber, PostalCode) values (35, 'Wayne Allen', 'Kentucky', 'Kinsman', '0', '40524');
